apiVersion: v1
kind: Secret
metadata:
  name: aws-creds
  namespace: mem
stringData:
  creds: |
    [default]
    aws_access_key_id = test
    aws_secret_access_key = test
---
apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: aws-creds
      namespace: mem
      key: creds
  skip_credentials_validation: true
  skip_region_validation: true
  skip_metadata_api_check: true
  skip_requesting_account_id: true
  s3_use_path_style: true
  endpoint:
    hostnameImmutable: true
    services:
    - s3
    - s3control
    - sts
    - iam
    - resourcegroupstaggingapi
    url:
      type: Static
      static: http://localstack.mem.svc.cluster.local:4566
