apiVersion: v1
kind: Pod
metadata: {name: orch, namespace: mem}
spec:
  serviceAccountName: provider-aws-s3
  restartPolicy: Never
  containers:
  - name: orch
    image: alpine:3.22
    command: ["/bin/sh", "/cfg/orch.sh"]
    volumeMounts:
    - {name: cfg, mountPath: /cfg}
    - {name: bin, mountPath: /hostbin, readOnly: true}
    - {name: out, mountPath: /hostout}
  volumes:
  - {name: cfg, configMap: {name: orch}}
  - {name: bin, hostPath: {path: /provider-bin}}
  - {name: out, hostPath: {path: /provider-bin}}
